sudo: required
language: python
python: 3.6

env:
  - NODE_VERSION="7"

addons:
  ssh_known_hosts:
    - vps.jarrekk.com

before_install:
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - nvm --version

before_script:
  - pip install Fabric3
  - openssl aes-256-cbc -K $encrypted_6b6147749537_key -iv $encrypted_6b6147749537_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

script:
  - fab front

notifications:
  email: me@jarrekk.com
